//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace evencat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuaris
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuaris()
        {
            this.Esdeveniments = new HashSet<Esdeveniments>();
            this.Reserves = new HashSet<Reserves>();
            this.Usuaris1 = new HashSet<Usuaris>();
        }
    
        public int usuari_id { get; set; }
        public string email { get; set; }
        public string password_hash { get; set; }
        public string rol { get; set; }
        public Nullable<System.DateTime> data_registre { get; set; }
        public Nullable<int> created_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esdeveniments> Esdeveniments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserves> Reserves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuaris> Usuaris1 { get; set; }
        public virtual Usuaris Usuaris2 { get; set; }
    }
}
